// This file is auto-generated by @hey-api/openapi-ts

export { getError, getFightChicken, getHealth, getItems, getServerStatus, getTest, type Options } from './sdk.gen';
export type { ClientOptions, GetErrorData, GetErrorResponses, GetFightChickenData, GetFightChickenResponses, GetHealthData, GetHealthResponse, GetHealthResponses, GetItemsData, GetItemsError, GetItemsErrors, GetItemsResponse, GetItemsResponses, GetServerStatusData, GetServerStatusError, GetServerStatusErrors, GetServerStatusResponses, GetTestData, GetTestResponses, HealthStatus, Item, Problem } from './types.gen';
