// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetErrorData, GetErrorResponses, GetFightChickenData, GetFightChickenResponses, GetHealthData, GetHealthResponses, GetItemsData, GetItemsErrors, GetItemsResponses, GetServerStatusData, GetServerStatusErrors, GetServerStatusResponses, GetTestData, GetTestResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getItems = <ThrowOnError extends boolean = false>(options?: Options<GetItemsData, ThrowOnError>): RequestResult<GetItemsResponses, GetItemsErrors, ThrowOnError> => (options?.client ?? client).get<GetItemsResponses, GetItemsErrors, ThrowOnError>({ url: '/items/', ...options });

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

export const getServerStatus = <ThrowOnError extends boolean = false>(options?: Options<GetServerStatusData, ThrowOnError>): RequestResult<GetServerStatusResponses, GetServerStatusErrors, ThrowOnError> => (options?.client ?? client).get<GetServerStatusResponses, GetServerStatusErrors, ThrowOnError>({ url: '/server-status', ...options });

export const getTest = <ThrowOnError extends boolean = false>(options?: Options<GetTestData, ThrowOnError>): RequestResult<GetTestResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetTestResponses, unknown, ThrowOnError>({ url: '/test', ...options });

export const getFightChicken = <ThrowOnError extends boolean = false>(options?: Options<GetFightChickenData, ThrowOnError>): RequestResult<GetFightChickenResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetFightChickenResponses, unknown, ThrowOnError>({ url: '/fight-chicken', ...options });

export const getError = <ThrowOnError extends boolean = false>(options?: Options<GetErrorData, ThrowOnError>): RequestResult<GetErrorResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetErrorResponses, unknown, ThrowOnError>({ url: '/error', ...options });
